### ISSUE TITLE
[Bug] - Can't open save file

### ISSUE THREAD

**Issue by 1951052175TranDucTai** [AnthonyMichaelTDM/DRG-Save-Editor#105]
#Traceback (most recent call last):
  File "main.py", line 384, in open_file
  File "main.py", line 1307, in init_values
  File "main.py", line 708, in get_weapons
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 0: invalid start byte
[76561198365258525_Player.zip](https://github.com/user-attachments/files/17113860/76561198365258525_Player.zip)

**Comment by Bogdanov89** [comment]
Hey thanks for this great tool, i just started using it.
I am getting the same error as above (after opening save file all fields are empty) but after clicking Reset to Original Values i also get the following:

Traceback (most recent call last):
File "main.py", line 1176, in reset_values
KeyError: 'season-initial'

No matter what i try editing the save process fails with those same error lines (key error season-initial).
Thanks for looking into these issues!

**Comment by wahlp** [comment]
i assume both of you are using the 1.9.1 release

both the issues described are resolved in the latest version of the code, but @AnthonyMichaelTDM hasn't yet put out a new release with those changes.

**Comment by AnthonyMichaelTDM** [comment]
Oops, thanks for reminding me, I’ll get to that soon

**Comment by AnthonyMichaelTDM** [comment]
release is building, should be done shortly
