### ISSUE TITLE
i'm new :(

### ISSUE THREAD

**Issue by Irkath** [AnthonyMichaelTDM/DRG-Save-Editor#11]
hey fellas, I have no experience doing anything like this. In the original save editor, I was able to run the start editor cmd and everything worked fine but for S3 I found this fork, and sadly I need more detailed instructions so if anyone could help or modify my save for me would be a lot of help thankyou :D

**Comment by AnthonyMichaelTDM** [comment]
#9

**Comment by AnthonyMichaelTDM** [comment]
please see #9 , if the marked answer doesn't work for you feel free to reopen this issue but until then I'm marking it as resolved
