### ISSUE TITLE
instructions makes absolutely no sense

### ISSUE THREAD

**Issue by TheTrueGraveDigger** [AnthonyMichaelTDM/DRG-Save-Editor#13]
how do I even use this thing, the guide makes sense whatsoever

**Comment by NerdyJosh1** [comment]
if you need help updating it i can help you just add me on discord NerdyJosh#3816

**Comment by TheTrueGraveDigger** [comment]
added, username is TheGraveDigger#7215

**Comment by SolidSombra** [comment]
May you help me to? @NerdyJosh1 Solid Judgement#0418

**Comment by NerdyJosh1** [comment]
I made a youtube video on how to update it 

https://www.youtube.com/watch?v=2h2-nZ2ptRo&ab_channel=NerdyJosh

**Comment by AnthonyMichaelTDM** [comment]
#9
