### ISSUE TITLE
Fixed tab order by organizing editor.ui structure

### ISSUE THREAD

**Issue by bbeenn1** [AnthonyMichaelTDM/DRG-Save-Editor#17]
### CAUTION: I set the **font size** to be all identical in the process
Had an issue I noticed previously with the `editor.ui` file being all over the place (like it was created with a gui tool or something). 
This resulted in a very bad tab order.

I am attaching the modified `editor.ui` file I worked on. 
_In order to add it to this message I had to rename it to `editor.ui.txt`._
Download this: >>> [editor.ui.txt](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/files/9955655/editor.ui.txt) <<<

To Use this file: 
1. Backup your existing `editor.ui` _just in case_
2. Download the attached >>> [editor.ui.txt](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/files/9955655/editor.ui.txt) <<<
3. RENAME the downloaded file to `editor.ui` (Make sure you can see the file extension in File Explorer, it's important!)
4. Copy/Move the downloaded `editor.ui` file to the root folder (the same folder `guids.json` is in)

## The Reason the font size was changed by me
_I use DPI scaling at 150% on monitors with 4k resolution, so I couldn't read anything in the window (everything was absolutely huge). The font size will likely need to be adjusted for most people, current font size is set to 9 (which for me means 9 * 1.5 = 13.5) so the appropriate equivalent would be using 13 or 14 point font._

### To Change Font Size
Open the file and search for `<pointsize>9</pointsize>` and replace with what you want, i.e. `<pointsize>13</pointsize>`

I will see if I can apply the original values in a future post, but there were 4 distributed across things so it will take a bit of effort.

**Comment by AnthonyMichaelTDM** [comment]
> Had an issue I noticed previously with the `editor.ui` file being all over the place (like it was created with a gui tool or something). This resulted in a very bad tab order.

According to the original developer [here](https://github.com/robertnunn/DRG-Save-Editor/issues/10#issuecomment-811291913), they did indeed use a gui tool to design the layout of the app. 
It seems you have some knowledge on this matter so if you'd be willing to cleanup the editor.ui file and create a PR with those changes I'd appreciate it, and give you credit in the readme.

**Comment by bbeenn1** [comment]
I know it took a while. 
I believe the editor.ui file linked to this comment should work as-is _(only tested on my own machine at this point)_.

I did find as I was researching that every time QT Designer makes changes to the ui file it has the potential to "shuffle" widget entries, but I also have read that others were able to fix it by making certain they created items "programmatically" (or in the correct tab order). This _thankfully_ doesn't impact us, as we don't have QT Designer.

Some of the elements could be potentially fixed using different container "parents" but that may be more effort than it is worth since I got everything to this point already.

OLD _(on my 4k screen at 150% DPI)_
<img width="1211" alt="image" src="https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/5580320/2c8fc311-038c-4478-be94-91773c269f39">
[OLD.AMTDM.editor.ui.txt](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/files/11845858/OLD.AMTDM.editor.ui.txt)

NEW _(on my 4k screen at 150% DPI)_
<img width="1211" alt="image" src="https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/5580320/803cdee0-b9f5-447d-b602-ad7d18ae2c06">
[NEW.BRP.editor.ui.txt](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/files/11845860/NEW.BRP.editor.ui.txt)

All anyone has to do is download [NEW.BRP.editor.ui.txt](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/files/11845860/NEW.BRP.editor.ui.txt) to their machine, rename it to replace the existing editor.ui file, and launch the module.

Once I remember how to submit a pull request for a single file I will see about it, just don't use GitHub enough still.

**Comment by AnthonyMichaelTDM** [comment]
https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository
