### ISSUE TITLE
Text labels in UI look skewed [BUG]

### ISSUE THREAD

**Issue by kotsmotritnastul** [AnthonyMichaelTDM/DRG-Save-Editor#18]
This is how it looks
[i.imgur.com/Lkj5Sbi.png](https://i.imgur.com/Lkj5Sbi.png)

Is it problem with my fonts or with program itself? Menus are fine though.

**Comment by AnthonyMichaelTDM** [comment]
Might be a screen resolution issue, worth looking into though

**Comment by kotsmotritnastul** [comment]
my screen resolution is 1920*1080

**Comment by KeithDragoon** [comment]
I have a similar issue but a bit worse
![uh](https://user-images.githubusercontent.com/118141652/201551568-ff5952a6-7624-437d-8d0d-0394b9699e37.png)

**Comment by AnthonyMichaelTDM** [comment]
Oh yikes

**Comment by AnthonyMichaelTDM** [comment]
I'm busy with midterms rn but this is serious, I'll look into it when I have time.

Like always, I welcome contributions.

**Comment by AnthonyMichaelTDM** [comment]
before fixing this, I'm going to want to refactor the code-base, as it stands everything is in a single main.py module which is completely ridiculous.

**Comment by NightFeather0615** [comment]
> I have a similar issue but a bit worse https://imgur.com/tXxOiYd

I had the same problem, it's because PyQt needs some configuration to fit a high resolution display, you can try adding the following code before PyQt loads the GUI (at the top of the program entry).

```python
if __name__ == "__main__":
    if hasattr(Qt, 'AA_EnableHighDpiScaling'):
        QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)

    if hasattr(Qt, 'AA_UseHighDpiPixmaps'):
        QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True)
        
    ...
```

**Comment by guimape** [comment]
> I have a similar issue but a bit worse https://imgur.com/tXxOiYd

Mine is equal :C

**Comment by AnthonyMichaelTDM** [comment]
marking as closed, feel free to re-open though if needed
