### ISSUE TITLE
Adding new secondary overclocks won't save them

### ISSUE THREAD

**Issue by LIMUNADE** [AnthonyMichaelTDM/DRG-Save-Editor#2]
While adding them to the inventory the result specifically for this overclocks can't be saved.

**Comment by AnthonyMichaelTDM** [comment]
hi, could you give me more information? 

what overclocks have you already unlocked,

what overclocks did you try to add

what did you do to add them

anything else that may be helpfull

**Comment by LIMUNADE** [comment]
Sure thing. 

- As for unlocked, I've got everything except few new secondary ones. 
- Well same thing for this part. 
- In order to add them, I select all unacquired overclocks and press "add cores to inventory" 
Btw, you forgot to add new overclocks to the main 1.5 zip file, I had to manually replace guids file,

**Comment by AnthonyMichaelTDM** [comment]
Oh I didn't forget, look at the readme, the .zip is out of date bc the build system requires a paid account and I'm a broke college student

**Comment by AnthonyMichaelTDM** [comment]
Follow the instructions in the readme for instructions on running the up-to-date editor

**Comment by AnthonyMichaelTDM** [comment]
if you still have issues, please let me know

**Comment by LIMUNADE** [comment]
Honestly it's way too much effort to make up-to-date working editor using your alternative method. I'd rather wait till you will be rich in this "IT heavy" world or farm overclocks by doing chores.

**Comment by AnthonyMichaelTDM** [comment]
I'm marking this as closed, feel free to re-open if you think it's still an issue.

**Comment by AnthonyMichaelTDM** [comment]
btw, your issue is resolved in the latest release
