### ISSUE TITLE
Import name 'definitions' from 'lib'

### ISSUE THREAD

**Issue by Wayunn** [AnthonyMichaelTDM/DRG-Save-Editor#20]
After following the instructions and video tutorial I've been stuck with this error message. Running Python 3.10.8 and have tried other versions. (3.10.4, 3.9.9, 3.8.15)

1. Entered pip install -r ./requirements.txt with no problem
2. python ./src/main/python/main.py returns with the below error
```
PS C:\Users\itzal\Desktop\CxC\DRG-Save-Editor-master> python ./src/main/python/main.py
Traceback (most recent call last):
  File "C:\Users\itzal\Desktop\CxC\DRG-Save-Editor-master\src\main\python\main.py", line 17, in <module>
    from lib import definitions
ImportError: cannot import name 'definitions' from 'lib' (C:\Users\itzal\AppData\Local\Programs\Python\Python310\lib\site-packages\lib\__init__.py)
```

**Comment by AnthonyMichaelTDM** [comment]
That's an error on my end resulting from the most recent commit, I'll revert in the morning, in the meantime use the code in the v1.7.0 release

**Comment by Wayunn** [comment]
That did the trick, thanks for the fast response and for updating this tool!

**Comment by AnthonyMichaelTDM** [comment]
yeah no worries, it should be fixed in the master branch too now
