### ISSUE TITLE
python3 ./src/main/python/main.py > Python not found

### ISSUE THREAD

**Issue by Vianns** [AnthonyMichaelTDM/DRG-Save-Editor#22]
Hello !

Just followed your instructions to install the program (running _pip install -r ./requirements.txt_ twice), but when I start the _python3 ./src/main/python/main.py_ command, I get a "Python is not found" error message.
What could cause this ?

Thanks.

**Comment by Vianns** [comment]
Python 3.10 is installed btw.

**Comment by DW256** [comment]
try using `python ./src/main/python/main.py`
without "3"

**Comment by Vianns** [comment]
It works, thanks!
