### ISSUE TITLE
im so confused

### ISSUE THREAD

**Issue by ajm0208** [AnthonyMichaelTDM/DRG-Save-Editor#23]
I've been following the guide NerdyJosh made but when I put in the pip install -r ./requirements.txt command it gives me back:

Fatal error in launcher: Unable to create process using '"C:\Users\MyName\AppData\Local\Programs\Python\Python310\python.exe"  "C:\Users\MyName\AppData\Local\Programs\Python\Python310\Scripts\pip.exe" install -r ./requirements.txt': The system cannot find the file specified.

Im using the 3.10 version from the windows store which he said to do but its still not working and none of the comments on the video have this issue.

**Comment by AnthonyMichaelTDM** [comment]
The file isn't in the directory your terminal is open in

**Comment by AnthonyMichaelTDM** [comment]
Error codes can be very informative when you read them

**Comment by Hatsune-Mikun** [comment]
Should you just make ZIP file as did it first author, and put into release, for users, who don't want download python and build the project?

Imma JS developer, not sure i want to make my own editor, but don't want install Python on my PC, zip was very useful, but previous author idk why put it into project files, not into release

It must don't take much time
Thanks for you work

**Comment by ajm0208** [comment]
> The file isn't in the directory your terminal is open in

You mean the requirements.txt file? It is in the directory.

**Comment by AnthonyMichaelTDM** [comment]
Sure, but the error code is saying that the file doesn't exist, try running 'pwd' that should tell you where your terminal is opened, you can also use the ls command to print the contents of the current directory and the cd command to navigate through directories

**Comment by AnthonyMichaelTDM** [comment]
> Should you just make ZIP file as did it first author, and put into release, for users, who don't want download python and build the project?
> 
> 
> 
> Imma JS developer, not sure i want to make my own editor, but don't want install Python on my PC, zip was very useful, but previous author idk why put it into project files, not into release
> 
> 
> 
> It must don't take much time
> 
> Thanks for you work

Whether or not I should is a debatable subject, but the fact of the matter is that the software used to package the Python code into a standalone executable binary is not free. Im in college right now and I have better things to spend my money on.

Previously, someone gave me a tarball of the software that theoretically would work but I haven't had the time to dig through it and verify its authenticity.

**Comment by ajm0208** [comment]
> Sure, but the error code is saying that the file doesn't exist, try running 'pwd' that should tell you where your terminal is opened, you can also use the ls command to print the contents of the current directory and the cd command to navigate through directories

I used pwd and it verified that the terminal is open in DRG-Save-Editor-master and ls shows that requirements.txt is in the directory, and it still doesn't work.

**Comment by AnthonyMichaelTDM** [comment]
Can you send screenshots along with the exact commands you used?

**Comment by ajm0208** [comment]
> Can you send screenshots along with the exact commands you used?

![Screenshot 2023-02-19 155444](https://user-images.githubusercontent.com/116618419/219974646-b259f5ae-0c02-4238-97a1-3cb304180b21.png)

**Comment by AnthonyMichaelTDM** [comment]
Try `python -m pip install -r requirements.txt`

**Comment by ajm0208** [comment]
> Try `python -m pip install -r requirements.txt`

![Screenshot 2023-02-19 191943](https://user-images.githubusercontent.com/116618419/219984385-78bbbbfb-24d9-4391-8c5a-abbc1002902b.png)

**Comment by AnthonyMichaelTDM** [comment]
Python either isn't installed properly, or hasn't been added to your path variable

Try: 
- `py`instead of `python`
- Opening a new terminal and trying again (if you downloaded Python when the terminal was open, the path variable wouldn't refresh yet)
- reinstalling Python as per video instructions from the windows store
- using the path to the Python exe instead of just "python"

**Comment by ajm0208** [comment]
> Python either isn't installed properly, or hasn't been added to your path variable
> 
> Try:
> 
> * `py`instead of `python`
> * Opening a new terminal and trying again (if you downloaded Python when the terminal was open, the path variable wouldn't refresh yet)
> * reinstalling Python as per video instructions from the windows store
> * using the path to the Python exe instead of just "python"

I installed it from the website instead and it literally worked immediately so I think the windows store version just doesn't work. Might be worth saying to the guy who made the video.
