### ISSUE TITLE
[Proposal] - Add "Rocket Barrage" Weapon Overclock and Remove "Manual Guidance Cutoff"

### ISSUE THREAD

**Issue by WayneYellow** [AnthonyMichaelTDM/DRG-Save-Editor#32]
It is known that the "Hurricane" Guided Rocket System was updated with a new overclock "rocket barrage" not long ago and the "manual guidance cutoff" has been removed, but the save editor has not made these changes, hope someone can fix it.

**Comment by AnthonyMichaelTDM** [comment]
Is the change just in name or have the guid’s changed too?On Aug 8, 2023, at 6:54 AM, 黃楚文 ***@***.***> wrote:﻿
It is known that the "Hurricane" Guided Rocket System was updated with a new overclock "rocket barrage" not long ago and the "manual guidance cutoff" has been removed, but the save editor has not made these changes, hope someone can fix it.

**Comment by WayneYellow** [comment]
I did a test and it looks like the new overclock replaced the old one, so the GUID now corresponds to the new overclock. So I think just need to change the name. I'll do a pull requests later.
