### ISSUE TITLE
Unable to add overclocks or edit seasonal progress

### ISSUE THREAD

**Issue by Divinehero1** [AnthonyMichaelTDM/DRG-Save-Editor#36]
i should have everything properly installed and yet season stuff is greyed out once i actually load my save and  if i add overclocks then save they don't show up in the forge for me to craft so i reload my save in the editor and whatever OCs i added aren't there

**Comment by AnthonyMichaelTDM** [comment]
Have you unlocked OCs yet in-game?Sent from my iPhoneOn Aug 25, 2023, at 1:26 PM, Divinehero1 ***@***.***> wrote:﻿
i should have everything properly installed and yet season stuff is greyed out once i actually load my save and  if i add overclocks then save they don't show up in the forge for me to craft so i reload my save in the editor and whatever OCs i added aren't there

**Comment by Divinehero1** [comment]
yea i have overclocks unlocked i got every class at bronze 3 or higher atm

**Comment by AnthonyMichaelTDM** [comment]
Can you reproduce the bug? (Provide steps too preferably)Sent from my iPhoneOn Aug 25, 2023, at 2:49 PM, Divinehero1 ***@***.***> wrote:﻿
yea i have overclocks unlocked i got every class at bronze 3 or higher atm

**Comment by Divinehero1** [comment]
um.. i just launch the start editor.cmd load up my file and add an unacquired overclock to my unforged pool save it and go in game to find it's not available to craft so i close the game and reload my save in the editor to find the overclocks i added not being there

while w/ the seasonal stuff i notice the stuff is "editable" before i load a save but once i do it's greyed out.. it makes me wonder if something else controls it

**Comment by AnthonyMichaelTDM** [comment]
Can you make a video?Sent from my iPhoneOn Aug 26, 2023, at 12:29 AM, Divinehero1 ***@***.***> wrote:﻿
um.. i just launch the start editor.cmd load up my file and add an unacquired overclock to my unforged pool save it and go in game to find it's not available to craft so i close the game and reload my save in the editor to find the overclocks i added not being there
while w/ the seasonal stuff i notice the stuff is "editable" before i load a save but once i do it's greyed out.. it makes me wonder if something else controls it

**Comment by Divinehero1** [comment]
i uh.. wouldn't know how to

**Comment by AnthonyMichaelTDM** [comment]
Preferably screen record with obs and upload to YouTube or something Sent from my iPhoneOn Aug 26, 2023, at 12:36 PM, Divinehero1 ***@***.***> wrote:﻿
i uh.. wouldn't know how to

**Comment by AnthonyMichaelTDM** [comment]
okay actually, thinking about this for a bit I think you may be working on https://github.com/robertnunn/DRG-Save-Editor because we no longer use editor.cmd to start the editor, try reinstalling with the instructions in this repository and report back whether the issue persists please.

thank you

**Comment by Divinehero1** [comment]
um i downloaded the source off this specific github then followed the instructions but uh.. i'll try reinstalling

**Comment by AnthonyMichaelTDM** [comment]
it's just that I don't see an editor.cmd in this repo, we start the editor directly with python

**Comment by Divinehero1** [comment]
....huh and now it works? despite following basically the same steps

**Comment by AnthonyMichaelTDM** [comment]
Glad to hear that your issue is solved

**Comment by Divinehero1** [comment]
kinda unrelated but how would i make a shortcut of sorts so i don't need to open powershell in that folder and put in that command everytime i wanna use it
