### ISSUE TITLE
[ISSUE/ERROR] Editor dont work properly after last game update 

### ISSUE THREAD

**Issue by kiri445566** [AnthonyMichaelTDM/DRG-Save-Editor#42]
Its doest add overclocks

![python3 10_A9ignKHiHv](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/64708592/564a7c6d-4547-45b2-b99b-8801b2ecb689)

![python3 10_GwOYtCwQOL](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/64708592/f282cf5a-4111-4658-b4f9-beab43faaac5)

![20231118202415_1](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/64708592/4018bd1e-f064-4905-a4f5-7cef93647eb2)

**Comment by ASmolKitten** [comment]
Season XP is also broken.

**Comment by AnthonyMichaelTDM** [comment]
Can you do me a favor and translate that error screen (the in game screenshot) to English?

**Comment by kiri445566** [comment]
> The last screen is just showing that there are no cores and how to get them normally.

oh, man, thank you, I was thinking, what should I do with the cells....

**Comment by kiri445566** [comment]
> Can you do me a favor and translate that error screen (the in game screenshot) to English?

....

it says that i dont have overclocks

**Comment by bbeenn1** [comment]
I believe the addition of Seasonal "Weapon Experience" is related to this issue.

**Comment by AnthonyMichaelTDM** [comment]
can you check if this is still an issue in the latest release

**Comment by AnthonyMichaelTDM** [comment]
Closing, reopen if it's still an issue

**Comment by kiri445566** [comment]
reiopen
