### ISSUE TITLE
[BUG] Season XP

### ISSUE THREAD

**Issue by ASmolKitten** [AnthonyMichaelTDM/DRG-Save-Editor#44]
Console Output after trying to edit season XP:
---
PS C:\Users\a\Desktop\DRG-Save-Editor-master\DRG-Save-Editor-master> python ./src/main/python/main.py
Traceback (most recent call last):
  File "C:\Users\a\Desktop\DRG-Save-Editor-master\DRG-Save-Editor-master\src\main\python\main.py", line 1273, in <module>
    exit_code = appctext.app.exec_()
  File "C:\Users\a\Desktop\DRG-Save-Editor-master\DRG-Save-Editor-master\src\main\python\main.py", line 69, in focusOutEvent
    widget.season_xp_.setText("0")
AttributeError: 'PySide2.QtWidgets.QMainWindow' object has no attribute 'season_xp_'

**Comment by Scrymen** [comment]
I have the same problem... Did you find any solution?

**Comment by bbeenn1** [comment]
This error shows when the editor tries to write to the temporary save file.
Removing the typo on line 69 in `main.py` removes the console error.
i.e. 
from 
```             elif box.endswith("lvl_text"):
                if value < 0:
                    widget.season_lvl_text.setText("0")
                elif value > 100:
                    widget.season_lvl_text.setText("100")
                    widget.season_xp_.setText("0")
```
to
```            elif box.endswith("lvl_text"):
                if value < 0:
                    widget.season_lvl_text.setText("0")
                elif value > 100:
                    widget.season_lvl_text.setText("100")
                    widget.season_xp.setText("0")
```
This condition should only happen if you are over level 100 for the season.

I have been having issues with the wrong values showing for the current season and believe it is related to the addition of Seasonal "Weapon Experience" about a month ago now.

**Comment by AnthonyMichaelTDM** [comment]
Could you make a pr for this?On Dec 23, 2023, at 2:11 AM, Ben ***@***.***> wrote:﻿
This error shows when the editor tries to write to the temporary save file.
Removing the typo on line 69 in main.py removes the console error.
i.e.
from
                if value < 0:
                    widget.season_lvl_text.setText("0")
                elif value > 100:
                    widget.season_lvl_text.setText("100")
                    widget.season_xp_.setText("0")

to
                if value < 0:
                    widget.season_lvl_text.setText("0")
                elif value > 100:
                    widget.season_lvl_text.setText("100")
                    widget.season_xp.setText("0")

This condition should only happen if you are over level 100 for the season.
I have been having issues with the wrong values showing for the current season and believe it is related to the addition of Seasonal "Weapon Experience" about a month ago now.

**Comment by bbeenn1** [comment]
Since I suck at GitHub that involves forking first, creating a branch on my own copy, then creating a pull request referencing my branch, correct?
