### ISSUE TITLE
editor gives error when starting [BUG]

### ISSUE THREAD

**Issue by AxoCat** [AnthonyMichaelTDM/DRG-Save-Editor#46]
**Describe the bug**
editor gives error when starting

**To Reproduce**
1. try starting the editor via terminal
2. error

**Expected behavior**
the editor starting

**Save File**
unnecessary

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
command:

python3 ./src/main/python/main.py

this is what appears in terminal:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

**Checklist**
- [X] I know how to use check boxes
- [X] I am using the most recent version of the editor
- [X] I have installed the editor and all it's dependencies correctly (see [this video tutorial](https://www.youtube.com/watch?v=2h2-nZ2ptRo) if you're on windows)
- [X] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
- [X] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously

**Comment by AnthonyMichaelTDM** [comment]
Try setting the environment variable as suggested by the error message, this seems to be more of a wayland/Qt issueOn Dec 4, 2023, at 7:42 AM, AxoCat ***@***.***> wrote:﻿
Assigned #46 to @AnthonyMichaelTDM.

**Comment by AxoCat** [comment]
This it my first time using python so i have no idea how to do that, could you tell me what i'm supposed to put into the terminal to make it work?

**Comment by bbeenn1** [comment]
Since I suck at GitHub that involves forking first, creating a branch on my own copy, then creating a pull request referencing my branch, correct?

**Comment by AnthonyMichaelTDM** [comment]
`QT_QPA_PLATFORM=wayland python3 ./src/main/python/main.py`
iirc
