### ISSUE TITLE
Resetting the save(help)

### ISSUE THREAD

**Issue by Error384** [AnthonyMichaelTDM/DRG-Save-Editor#48]
When changing the level of the battle pass, the save is reset to 0 (steam cloud off)
![sdasd](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/154760219/856b388c-aa15-47f4-ba1d-8abad8e67f28)
![asdase](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/154760219/69749984-c915-41ba-90eb-1891c432b726)

**Comment by AnthonyMichaelTDM** [comment]
restore one of the backups that are automatically created, this is probably because I haven't updated this to the newest season
