### ISSUE TITLE
[BUG] Save Editor not changing anything

### ISSUE THREAD

**Issue by GhastyGhasty** [AnthonyMichaelTDM/DRG-Save-Editor#55]
**Describe the bug**
Basically I lost my old save file and I don't really wanna re-level all my characters again, I don't mind grinding out the weapons and stuff tho so It's okay, so I just want to increase the levels of my dwarfs but when I do so the game essentially just goes back to the tutorial

**To Reproduce**
1. I followed the video tutorial on how to use the Save Editor
2. I opened my save file using the Save Editor
3. I used the "Mass Actions" tab and used "XP Operations" then "Set all classes to 25"
4. I save the file
5. I opened the game and it just goes back to the tutorial

**Expected behavior**
I thought I would get a brand new start but with leveled up dwarfs

**Save File**
I see no point since I freshly bought the game but here it is
[76561198929509929_Player.zip](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/files/14735500/76561198929509929_Player.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
No Additional Context, hopefully I get help as soon as possible

**Checklist**
- [✓] I know how to use check boxes
- [✓] I am using the most recent version of the editor
- [✓] I have installed the editor and all it's dependencies correctly (see [this video tutorial](https://www.youtube.com/watch?v=2h2-nZ2ptRo) if you're on windows)
- [X] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
- [✓] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously

**Comment by GhastyGhasty** [comment]
Hi! I just wanted to add that when I opened the save file again it seemed to have made the values of every resource to it's max and whenever I would change them back to 0 it just reverts back

**Comment by AnthonyMichaelTDM** [comment]
can you check if this is still an issue in the latest release

**Comment by AnthonyMichaelTDM** [comment]
Closing, please reopen if it's still an issue
