### ISSUE TITLE
[BUG] Seasonal progress is broken

### ISSUE THREAD

**Issue by zhildirbek** [AnthonyMichaelTDM/DRG-Save-Editor#56]
**Describe the bug**
Did everything as instructed. Everything is displayed as is in the game except for the seasonal progress (which is exactly what I want to change). The numbers are just nonsensical and trying to change anything results in the save getting corrupted and reset to 0.

![image](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/166867152/46c52ca6-f7a8-420f-ae0a-f2870a75f0b6)

**To Reproduce**
1. Open the editor
2. Load a save

**Expected behavior**
The editor is supposed to be able to change my seasonal lvl 

**Save File**
[save.zip](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/files/14962966/save.zip)

**Desktop (please complete the following information):**
 - OS: Windows10
 - 
**Checklist**
- [x] I know how to use check boxes
- [x] I am using the most recent version of the editor
- [x] I have installed the editor and all it's dependencies correctly (see [this video tutorial](https://www.youtube.com/watch?v=2h2-nZ2ptRo) if you're on windows)
- [x] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
- [x] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously

**Comment by AnthonyMichaelTDM** [comment]
@zhildirbek this should've been fixed by #62, if you still have the issue please feel free to re-open, but in the meantime I'm marking this closed
