### ISSUE TITLE
qt.qpa.plugin error

### ISSUE THREAD

**Issue by oguzzct** [AnthonyMichaelTDM/DRG-Save-Editor#57]
somebody already mentioned this exact issue but it was a little old and there were no solutions found so here i am
when i run the command:
python ./src/main/python/main.py
i get this error:
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
i ran the
pip install -r requirements.txt
command already but that said every requirement was already satisfied
i don't know what to do, help please.
![resim_2024-04-12_234008044](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/166870223/4be0d265-a931-492d-8c20-b3761648dafc)

**Comment by AnthonyMichaelTDM** [comment]
Are you using the right Python version?

**Comment by oguzzct** [comment]
yes i am using python 10 as suggested in the tutorial video

**Comment by AnthonyMichaelTDM** [comment]
can you check if this is still an issue in the latest release

**Comment by oguzzct** [comment]
i just checked my mail and saw your response. no it isn't an issue anymore it works perfectly. i love the new design, it's so much easier to use and navigate through! love the updates too! good work man, thanks.
