### ISSUE TITLE
qt.qpa.plugin:

### ISSUE THREAD

**Issue by aim-wws** [AnthonyMichaelTDM/DRG-Save-Editor#59]
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Python 3.10.
fbs, PyQt5, PySide2 is installed.
Did it like in the video.

And how to fix it?

**Comment by AnthonyMichaelTDM** [comment]
can you see if this is still an issue in the latest release?
