### ISSUE TITLE
update for season 5

### ISSUE THREAD

**Issue by TheTrueGraveDigger** [AnthonyMichaelTDM/DRG-Save-Editor#61]
Season 5 came out so this needs updated

**Comment by SubjectV768** [comment]
bump, update please!

**Comment by FIobert** [comment]
Some users reported that the editor wiped to level 1, all resources at 0, and a brand new save altogether. 
Would wait for an update for season 5.

**Comment by subtera745** [comment]
what's it take to update for season 5?

**Comment by SubjectV768** [comment]
do we know if the makers of this are still dedicated? are we getting an update?

**Comment by AnthonyMichaelTDM** [comment]
As far as transparency goes, I haven’t played the game in years.
As far as what it takes to get a new season working, should just need the season GUID

**Comment by SubjectV768** [comment]
Is that something you intend to do? Hoping yes!

**Comment by AnthonyMichaelTDM** [comment]
idk honestly, but if someone opens a PR for it, I'll merge as long as someone else can confirm it works.

**Comment by subtera745** [comment]
well, I just bought the game so I've essentially got a fresh install to run tests on. Im pretty busy myself so if someone could tell me what branch specifically is the best bet or the like, I'll give it a go.

**Comment by SubjectV768** [comment]
Looking forward to hearing when the update is up and running!

**Comment by Saniee** [comment]
I have an all OC save if anyone needs it.

**Comment by emperorofstone** [comment]
> I have an all OC (guns, not cosmetics) save if anyone needs it.

Can i have it

**Comment by Saniee** [comment]
> > I have an all OC (guns, not cosmetics) save if anyone needs it.
> 
> Can i have it

[save.zip](https://github.com/user-attachments/files/15945536/save.zip)

**Comment by SubjectV768** [comment]
> idk honestly, but if someone opens a PR for it, I'll merge as long as someone else can confirm it works.

any updates on this? idk how any of this works

**Comment by xXramzS** [comment]
eagerly waiting for season 5 support, not sure how i can help since i've never worked with hex before, but if there's anything i can do i'd love to help

**Comment by SubjectV768** [comment]
pull request! is it time??
