### ISSUE TITLE
[BUG] editor not starting up

### ISSUE THREAD

**Issue by Shino101** [AnthonyMichaelTDM/DRG-Save-Editor#66]
imma be honest i have no clue how python works and I'm just listening to what i can find online.
is installed python Python v3.10 and got the requirements via `pip install -r ./requirements.txt` 
but when i try to start it using the `python ./src/main/python/main.py` command it pops up with the error:

ModuleNotFoundError: No module named 'PySide2'
PS C:\Users\yvoha\Desktop\DRG\DRG-Save-Editor-master\DRG-Save-Editor-master>

i have no idea what i need to do to fix it but help would be appreciated

**Comment by simon-wg** [comment]
Assuming you're on windows, try installing python 3.10.
PySide2 has not yet been updated for later versions of python.

**Comment by simon-wg** [comment]
can you open a terminal and run `python --version` and post the output here?

**Comment by ASmolKitten** [comment]
I had the same issue, double check you have done pip install -r ./requirements.txt since the last update, I had to do it again after the most recent merge. redoing the requirments.txt fixed it for me

**Comment by AnthonyMichaelTDM** [comment]
going to close this because the executables in the new release(s) should eliminate this kind of issue
