### ISSUE TITLE
[BUG] Segfault on Linux

### ISSUE THREAD

**Issue by t-lessy** [AnthonyMichaelTDM/DRG-Save-Editor#69]
**Describe the bug**
Segmentation fault on Linux.
```sh
z@tlessy:~/oh/DRG-Save-Editor$ python ./src/main/python/main.py
Ошибка сегментирования (образ памяти сброшен на диск)
```
This means "Segmentation fault (Core dumped)"

**To Reproduce**
1. Clone repo and install requirements.
2. Start script as written in readme.
3. Error appeared and app doesn't start.

**Expected behavior**
Starting the app and successfully editing saves.

**Save File**
Rather not to upload saves as there's no problem with it, sorry.

**Desktop:**
 - OS: Fedora Workstation 40 with LTS Kernel 6.1.97 from non-official repository.

**Additional context**
I have 32gb RAM, probably this has some matter.

**Checklist**
- [x] I know how to use check boxes
- [x] I am using the most recent version of the editor
- [x] I have installed the editor and all it's dependencies correctly (see [this video tutorial](https://www.youtube.com/watch?v=2h2-nZ2ptRo) if you're on windows)
- [x] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
- [x] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously

**Comment by t-lessy** [comment]
Sorry, forgot to name issue!

**Comment by AnthonyMichaelTDM** [comment]
Was there no stack trace?

**Comment by AnthonyMichaelTDM** [comment]
@t-lessy can you run `python --version` and tell me what it says?

**Comment by t-lessy** [comment]
Hello! I just reinstalled my system, and so can't properly use Python, because of moved from Fedora to Ubuntu. I remembered that I was using Python newer than 3.10. Probably, that was an issue. Yeah, I forgot to check Py version.

Also, compiled app starts, but gives an error when saving. In game nothing changes, file are not edited as result. Using 1.9.0 release.
```sh
Traceback (most recent call last):
  File "main.py", line 789, in save_changes
  File "main.py", line 1028, in make_save_file
KeyError: 1
```

Sorry for unexpectedly ruining the proccess. 😔

**Comment by AnthonyMichaelTDM** [comment]
Seems related to #79 then

**Comment by AnthonyMichaelTDM** [comment]
can you send your save file? I'm trying to debug your issue rn but am having a hard time replicating the bug.

**Comment by AnthonyMichaelTDM** [comment]
@t-lessy can you see if #77 fixes the problem for you?
