### ISSUE TITLE
[Proposal] - Migrate from PySide2 to PySide6 (Qt5 -> Qt6)

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [AnthonyMichaelTDM/DRG-Save-Editor#72]
Migrating from pyside2 to pyside6 shouldn't be too difficult and should allow this project to run on the latest version(s) of python.

Going to wait for #68 #64 and #71 before I start this, just to prevent conflicts and whatnot.

**Comment by AnthonyMichaelTDM** [comment]
Note: this will be the final change before releasing v1.9.0

**Comment by AnthonyMichaelTDM** [comment]
@simon-wg , @wahlp , what are your thoughts on moving forward with this?
It'd make using this tool on linux easier (by supporting python 3.12, meaning most linux users can just use their systems' python distribution without having to download an older version (e.g. 3.10)), but I don't know how that would effect things on the windows side of things, do you guys have any inputs / insights?

**Comment by wahlp** [comment]
i think most users are on Windows and will go for the executable once it becomes available, so they wouldn't be concerned with the Python version unless they're also a developer.

developers like me might have to update their environment but i'm ok with that.

**Comment by AnthonyMichaelTDM** [comment]
> i think most users are on Windows and will go for the executable once it becomes available, so they wouldn't be concerned with the Python version unless they're also a developer.
> 
> developers like me might have to update their environment but i'm ok with that.

that makes sense

**Comment by AnthonyMichaelTDM** [comment]
pr is open if you want to take a look

**Comment by simon-wg** [comment]
I think it's a good idea to migrate. I don't see that the requirement of a more recent python version would be a major problem for anyone. PR looks good, I've added some comments regarding warnings on linux.
