### ISSUE TITLE
Editor is not saving.

### ISSUE THREAD

**Issue by mallard22** [AnthonyMichaelTDM/DRG-Save-Editor#77]
I am trying out the new release for Windows (v1.9.0) with the exe file. 
I extracted to a folder on the desktop and ran the exe and was able to load my save and make changes.
However, no changes made are able to be saved. After saving and then closing the app, if I reopen it and load the save or enter game the changes are all reverted. I've tried running as admin and making sure the file and folders are not read only.
The date modified of the save file doesn't change either, the app is just not saving and I cannot seem to figure out why.

Thank you for your work and any help you can provide.

**Comment by wahlp** [comment]
try running the source code and see if you can save your changes with it?

**Comment by mallard22** [comment]
Thank you for the suggestion. I was able to solve the problem with it.
Using the source code has the terminal open, so when I tried to save, the terminal gave the error message: Missing data for season 1, please start the season first.
I've never played season 1, so I loaded up the save file in game, swapped to season 1, saved, and then the editor allowed me to save changes. I went ahead and tried it again with the standalone exe version as well and it allowed me to save just fine.

The problem was just never having started season 1. I was not making changes to any of the seasons so I didn't realize they needed to be started up at least once in the save file first and the standalone exe does not show the error messages but it makes sense now.

Thank you again for your time.

**Comment by AnthonyMichaelTDM** [comment]
This should be fixed by #84, @mallard22 if you have a backup of your save from before you started season 1, could you please check to see if there are issues editing that save with the changes made in this PR?

If you don't know how to do that, you can send me the save file so I can test it myself

**Comment by dataesucsdeek** [comment]
> try running the source code and see if you can save your changes with it?

can you like tell me how do i run a source code as an executable program..???

**Comment by AnthonyMichaelTDM** [comment]
There are instructions in the readme

**Comment by WACK-wooho** [comment]
Hello I installed the new save editor and also tried the the source cod and none worked any help? it says im missing multiple seasons.

**Comment by AnthonyMichaelTDM** [comment]
In game, just switch between every available season to populate your save-file

**Comment by WACK-wooho** [comment]
I tried but it wouldn't work.

**Comment by WACK-wooho** [comment]
Would external factors mess it up?

**Comment by AnthonyMichaelTDM** [comment]
maybe? idk, can you open a new issue with all the info in the template + screenshots and stuff?

**Comment by WACK-wooho** [comment]
Could you describe what you are asking more specifically? im kind of

 slow

**Comment by WACK-wooho** [comment]
Im apparently even missing season 6 and or seasons ive played
