### ISSUE TITLE
[BUG] UnicodeDecodeError When Initiating the Program

### ISSUE THREAD

**Issue by RuthlessNail** [AnthonyMichaelTDM/DRG-Save-Editor#79]
**Describe the bug**
Upon executing DRG-Save-Editor.exe from release, "UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 58967: illegal multibyte sequence" appears, and the script fails to run. 

The full error message:
```
Traceback (most recent call last):
  File "main.py", line 1349, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 58967: illegal multibyte sequence
```
<img width="250" alt="image" src="https://github.com/user-attachments/assets/029b385b-3c98-4366-be3a-1d238e4d31f7">

Upon switching to using the source version like I did before, the error persist, although, a slightly different error message is shown:
```
Traceback (most recent call last):
  File "C:\Users\[redact]\Document\DRG-Save-Editor-master\src\main\python\main.py", line 1469, in <module>
    guid_dict: dict[str, Any] = json.loads(g.read())
                                           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 56779: illegal multibyte sequence
```

The environment for running from source is correctly set up, I am using Python 3.10.11, I later switched to Python 3.12.4 and set up the environment again, and the exact error persist. I was able to get the editor working correctly using source from the pull request #62.

**To Reproduce**
For me, simply execute DRG-Save-Editor.exe, or run `python ./src/main/python/main.py` in the editor dictionary, the issue will appear. I do not believe this is a commonly occurring issue, as I have not seen other reporting it.

**Expected behavior**
The script would run and I would be greeted with the gui of the editor, which did not happen.

**Save File**
Not necessarily relevant for this case

**Desktop (please complete the following information):**
 - OS: Windows10
 - Python Version: Python 3.10.11 (Later Python 3.12.4, error persist)

**Additional context**
My OS is in another language, though there is no non-unicode lettering in the path, and my game is in English (which shouldn't be relevant I believe).

**Checklist**
- [x] I know how to use check boxes
- [x] I am using the most recent version of the editor
- [x] I have installed the editor and all it's dependencies correctly (see [this video tutorial](https://www.youtube.com/watch?v=2h2-nZ2ptRo) if you're on windows)
- [ ] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
- [x] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously

**Comment by wahlp** [comment]
position 58967 of `guids.json` points to the last character in the overclock name `SmЯt Trigger OS™`. i'm guessing that your Windows language or locale made the default encoding for Python something other than UTF-8.

should be solvable in the code by explicitly specifying the encoding.

**Comment by RuthlessNail** [comment]
> position 58967 of `guids.json` points to the last character in the overclock name `SmЯt Trigger OS™`. i'm guessing that your Windows language or locale made the default encoding for Python something other than UTF-8.
> 
> should be solvable in the code by explicitly specifying the encoding.

Ah! I see. That actually makes a lot of sense. Should be an easy fix then. I’ll report back the result tomorrow when I get to it.

**Comment by AnthonyMichaelTDM** [comment]
You could also try removing that character from the name
