### ISSUE TITLE
[BUG] saving wont save. no matter how many times i press it the changes arent kept

### ISSUE THREAD

**Issue by dataesucsdeek** [AnthonyMichaelTDM/DRG-Save-Editor#81]
cant explain it any further. and i need a solution asap.

**Comment by dataesucsdeek** [comment]
ctrl+s... nah. saving via button? nah.
making a seperate save file and editing that? nope.

**Comment by dataesucsdeek** [comment]
and i cant really give you a before and after file SINCE IVE BEEN MESSING AROUND WITH THIS FOR 10 MINUTES NOW SO THERE IS NO MORE BEFORE FILE.

**Comment by AnthonyMichaelTDM** [comment]
Might be related to #77, see that issue for a potential fox and report back if it works or not.

**Comment by dataesucsdeek** [comment]
> Might be related to #77, see that issue for a potential fix and report back if it works or not.

i already checked that, how the fuck do i run the source code????????? what???????????????????????
if the thing itself wont work. the source code not having an executable for me to RUN IT wont fix anything???

**Comment by dataesucsdeek** [comment]
+ no error messages popped up telling me ANYTHING.

**Comment by dataesucsdeek** [comment]
either my game has to be running while im save editing?????????? and it doesnt say that anywhere??????
or theres an issue. plain and simple.

**Comment by AnthonyMichaelTDM** [comment]
Firstly, you need to calm down, it's not helping anyone. I understand that you're frustrated, but keeping a level head is important when it comes to debugging issues and interacting with the open source community. 
Next, we have the issue templates for a reason, without details on your issue, the steps to reproduce it, your save file, etc. it is incredibly difficult for anyone to provide you with useful assistance.

**Comment by AnthonyMichaelTDM** [comment]
Error messages should get printed to the terminal

**Comment by AnthonyMichaelTDM** [comment]
> either my game has to be running while im save editing?????????? and it doesnt say that anywhere??????
> 
> or theres an issue. plain and simple.

You should not have the game running when you're editing save files, that's a recipe for disaster (corrupted saves)

**Comment by dataesucsdeek** [comment]
> Firstly, you need to calm down, it's not helping anyone. I understand that you're frustrated, but keeping a level head is important when it comes to debugging issues and interacting with the open source community. Next, we have the issue templates for a reason, without details on your issue, the steps to reproduce it, what happened vs what you expected to happen, your save file, etc. it is incredibly difficult for anyone to provide you with useful assistance.

its almost as if you did not even read my messages
steps to reproduce: be me, open program, use it, it wont save edit's.

and i didnt see ANY terminal where errors are being printed.

**Comment by dataesucsdeek** [comment]
"missing info"
i cant give you anything more than my word.

**Comment by dataesucsdeek** [comment]
> Error messages get printed to the terminal

there. is no terminal.
![Z1ErzadRTU](https://github.com/user-attachments/assets/436a2781-a226-4b2e-aa7c-b8171ae4b34d)

**Comment by dataesucsdeek** [comment]
and please explain to me how do i run the god damn source code?????

> Might be related to #77, see that issue for a potential fix and report back if it works or not.

**Comment by AnthonyMichaelTDM** [comment]
> > Firstly, you need to calm down, it's not helping anyone. I understand that you're frustrated, but keeping a level head is important when it comes to debugging issues and interacting with the open source community. Next, we have the issue templates for a reason, without details on your issue, the steps to reproduce it, what happened vs what you expected to happen, your save file, etc. it is incredibly difficult for anyone to provide you with useful assistance.
> 
> 
> 
> its almost as if you did not even read my messages
> 
> steps to reproduce: be me, open program, use it, it wont save edit's.
> 
> 
> 
> and i didnt see ANY terminal where errors are being printed.

Then we can't help you, sorry

**Comment by dataesucsdeek** [comment]
yeah fix your shitty progam that would help??????
carrying on someone elses legacy my ass

**Comment by AnthonyMichaelTDM** [comment]
You're entitled to your opinion.

Feel free to open a new issue when you can provide the information listed in the issue template.
