### ISSUE TITLE
[Bug] - ...

### ISSUE THREAD

**Issue by swatgreat** [AnthonyMichaelTDM/DRG-Save-Editor#95]
### Describe the bug

Whenever I Tried to open the exe file this window pops up
![image](https://github.com/user-attachments/assets/7bfb8ee5-ace7-48c5-b9ee-af91c6d38a6e)

### Save File

attach a copy of your save file from BEFORE any edits were attempted

### Environment

- OS: Windows 10

### Additional context

For example, if your issue is similar to an existing issue, you can link it here and explain how your issue is different. (this will help prevent your issue from being closed as a duplicate)

## Checklist

- [T] I know how to use check boxes
- [T] I am using the most recent version of the editor
- [T] I have installed the editor correctly:
  - Check only one:
    - [T] I have installed the editor from the releases page
    - [ ] I an running the editor from source
- [T] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
  - **Note**: If you do not attach a save file, it will be significantly harder (and in some cases impossible) to diagnose your issue
- [T] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously
- [T] I have filled out the issue template correctly, and to the best of my ability. If I have not, I understand that my issue may be closed with or without a response

**Comment by wahlp** [comment]
similar to #79 
fixed in #83 but not in the executable yet

**Comment by AnthonyMichaelTDM** [comment]
I'll be releasing v1.9.1 shortly, which will include a fix for this issue
